name: publish release

on:
  workflow_dispatch:
  release:
    types:
      - published

permissions:
  contents: write
  packages: write

jobs:
  publish-docker-images:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          # Build and push for Bookworm arm64
          docker buildx build --platform linux/arm64 \
            -f bookworm/arm64.dockerfile \
            --tag ghcr.io/kilianp07/pi-go-build-images:bookworm-arm64-${{ github.event.release.tag_name }} \
            --push .

          # Build and push for Bookworm armv7
          docker buildx build --platform linux/arm/v7 \
            -f bookworm/armv7.dockerfile \
            --tag ghcr.io/kilianp07/pi-go-build-images:bookworm-armv7-${{ github.event.release.tag_name }} \
            --push .

          # Build and push for Bullseye arm64
          docker buildx build --platform linux/arm64 \
            -f bullseye/arm64.dockerfile \
            --tag ghcr.io/kilianp07/pi-go-build-images:bullseye-arm64-${{ github.event.release.tag_name }} \
            --push .

          # Build and push for Bullseye armv7
          docker buildx build --platform linux/arm/v7 \
            -f bullseye/armv7.dockerfile \
            --tag ghcr.io/kilianp07/pi-go-build-images:bullseye-armv7-${{ github.event.release.tag_name }} \
            --push .
