---
    name: publish release
    
    on:
      workflow_dispatch:
      release:
        types:
          - published
    
    permissions:
      contents: write
      packages: write
    
    jobs:
      publish-docker-images:
        runs-on: ubuntu-latest
    
        strategy:
          matrix:
            arch: [arm64, armv7]
            os: [bullseye, bookworm]
    
        steps:
          - uses: actions/checkout@v4
    
          - name: Login to GitHub Container Registry
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
    
          - name: Build and Push Docker Image
            run: |-
              DOCKERFILE="${{ matrix.os }}/${{ matrix.arch }}.dockerfile"
              TAG="ghcr.io/kilianp07/pi-go-build-images:${{ matrix.os }}-${{ matrix.arch }}-${{ github.event.release.tag_name }}"
              
              echo "Building ${TAG} using ${DOCKERFILE}"
              
              docker build -f $DOCKERFILE . --tag $TAG
              docker push $TAG
    